名称：构建 iStore OS 24.10
触发条件:
这是 GitHub 仓库页面，标题为“.github/workflows/build-istoreos-24.10.yml · 工作流运行 · pcy0124m/istoreos-actions”。上下文。
 workflow_dispatch:
    inputs:
      局域网IP:
        描述：'设置局域网IP地址'

        默认值：'192.168.12.1'
      操作系统名称:
        description: '设置系统名称'
        必需：true
        默认值：'iStore OS'
      enable_wifi:
        description: '启用WiFi'
        必需：true
        default: false
        类型: 布尔值
      ssh:
        描述：通过 SSH 连接到 Actions
        必填项：否
        默认值：'false'
计划：
 - cron：0 16 * * *

env：
 REPO_URL：https://github.com/istoreos/istoreos
 FEEDS_CONF：feeds.conf
 CONFIG_FILE：.config
 DIY_P1_SH：scripts/diy-part1.sh
DIY_P2_SH：scripts/diy-part2.sh
 WORK_DIR：/mnt/workdir
UPLOAD_BIN_DIR为真
  上传固件: t
  UPLOAD_RELEASE: t真
 时区: sia/Shanghai
 GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build:
 runs-on: ${{ matrix.os }}
    超时时间（分钟）: 300
    strategy:
      matrix:
        REPO_BRANCH:
          - istoreos-25.10
        架构:
          - mt7621-sp-01b-25.10
        操作系统：
          - ubuntu-24.04
      fail-fast: false

    步骤：
    - 名称: 检出仓库
      使用: actions/checkout@v4

    - 名称: 检查服务器配置
      运行: |
        echo "若分配的服务器性能不足，务必及时取消，重新运行！"
        echo -e "------------------------------- CPU信息 -------------------------------\n"
        echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
        echo -e "CPU核心及版本信息: $(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo -e "------------------------------- 内存信息 -------------------------------\n"
        echo "已安装内存详细信息: "
        sudo lshw -short -C memory | grep GiB || true
