name: JDY‑Build iStore OS 24.10
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      lan_ip:
        description: '设置局域网IP地址'
        required: true
        default: '192.168.12.1'
      os_name:
        description: '设置系统名称'
        required: true
        default: 'iStore OS'
      enable_wifi:
        description: '启用WiFi'
        required: true
        default: false
        type: boolean
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
# schedule:
#   - cron: 0 16 * * *

env:
  REPO_URL: https://github.com/istoreos/istoreos
  REPO_BRANCH: istoreos-24.10
  FEEDS_CONF: mt7621-sp01b/feeds.conf
  CONFIG_FILE: mt7621-sp01b/.config
  DIY_P1_SH: scripts/diy-part1.sh
  DIY_P2_SH: scripts/diy-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Build Environment
        uses: istoreos/build-actions@main
        with:
          repo_url: ${{ env.REPO_URL }}
          repo_branch: ${{ env.REPO_BRANCH }}
          feeds_conf: ${{ env.FEEDS_CONF }}
          config_file: ${{ env.CONFIG_FILE }}
          diy_p1_sh: ${{ env.DIY_P1_SH }}
          diy_p2_sh: ${{ env.DIY_P2_SH }}
          upload_bin_dir: ${{ env.UPLOAD_BIN_DIR }}
          upload_firmware: ${{ env.UPLOAD_FIRMWARE }}
          upload_release: ${{ env.UPLOAD_RELEASE }}
          ssh: ${{ github.event.inputs.ssh }}
