name: JDY‑Build iStore OS 24.10
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      lan_ip:
        description: '设置LAN IP地址'
        required: true
        default: '192.168.10.1'
      os_name:
        description: '设置系统名称'
        required: true
        default: 'iStore OS'
      enable_wifi:
        description: '启用WiFi'
        required: true
        default: false
        type: boolean
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
   - cron: 0 16 * * *

env:
  REPO_URL: https://github.com/istoreos/istoreos
  REPO_BRANCH: istoreos-24.10
  FEEDS_CONF: feeds.conf
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build OpenWrt
        uses: P3TERX/Actions-OpenWrt@main
        with:
          repo_url: ${{ env.REPO_URL }}
          repo_branch: ${{ env.REPO_BRANCH }}
          feeds_conf: ${{ env.FEEDS_CONF }}
          config_file: ${{ env.CONFIG_FILE }}
          diy_p1_sh: ${{ env.DIY_P1_SH }}
          diy_p2_sh: ${{ env.DIY_P2_SH }}
          ssh: ${{ github.event.inputs.ssh }}
